//go:build !ignore_autogenerated

/*
Copyright 2026 Big Bang.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalPolicy) DeepCopyInto(out *AdditionalPolicy) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(AdditionalPolicyAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(AdditionalPolicyLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(AdditionalPolicySpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalPolicy.
func (in *AdditionalPolicy) DeepCopy() *AdditionalPolicy {
	if in == nil {
		return nil
	}
	out := new(AdditionalPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AdditionalPolicyAnnotations) DeepCopyInto(out *AdditionalPolicyAnnotations) {
	{
		in := &in
		*out = make(AdditionalPolicyAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalPolicyAnnotations.
func (in AdditionalPolicyAnnotations) DeepCopy() AdditionalPolicyAnnotations {
	if in == nil {
		return nil
	}
	out := new(AdditionalPolicyAnnotations)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AdditionalPolicyLabels) DeepCopyInto(out *AdditionalPolicyLabels) {
	{
		in := &in
		*out = make(AdditionalPolicyLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalPolicyLabels.
func (in AdditionalPolicyLabels) DeepCopy() AdditionalPolicyLabels {
	if in == nil {
		return nil
	}
	out := new(AdditionalPolicyLabels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AdditionalPolicySpec) DeepCopyInto(out *AdditionalPolicySpec) {
	{
		in := &in
		*out = make(AdditionalPolicySpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalPolicySpec.
func (in AdditionalPolicySpec) DeepCopy() AdditionalPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AdditionalPolicySpec)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppliedResource) DeepCopyInto(out *AppliedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppliedResource.
func (in *AppliedResource) DeepCopy() *AppliedResource {
	if in == nil {
		return nil
	}
	out := new(AppliedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Istio) DeepCopyInto(out *Istio) {
	*out = *in
	if in.Ambient != nil {
		in, out := &in.Ambient, &out.Ambient
		*out = new(IstioAmbient)
		**out = **in
	}
	if in.AuthorizationPolicies != nil {
		in, out := &in.AuthorizationPolicies, &out.AuthorizationPolicies
		*out = new(IstioAuthorizationPolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.Mtls != nil {
		in, out := &in.Mtls, &out.Mtls
		*out = new(IstioMtls)
		**out = **in
	}
	if in.ServiceEntries != nil {
		in, out := &in.ServiceEntries, &out.ServiceEntries
		*out = new(IstioServiceEntries)
		(*in).DeepCopyInto(*out)
	}
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(IstioSidecar)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Istio.
func (in *Istio) DeepCopy() *Istio {
	if in == nil {
		return nil
	}
	out := new(Istio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAmbient) DeepCopyInto(out *IstioAmbient) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAmbient.
func (in *IstioAmbient) DeepCopy() *IstioAmbient {
	if in == nil {
		return nil
	}
	out := new(IstioAmbient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPolicies) DeepCopyInto(out *IstioAuthorizationPolicies) {
	*out = *in
	if in.AdditionalPolicies != nil {
		in, out := &in.AdditionalPolicies, &out.AdditionalPolicies
		*out = make(IstioAuthorizationPoliciesAdditionalPolicies, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]IstioAuthorizationPoliciesCustomElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(IstioAuthorizationPoliciesDefaults)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPolicies.
func (in *IstioAuthorizationPolicies) DeepCopy() *IstioAuthorizationPolicies {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesAdditionalPolicies) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPolicies) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesAdditionalPolicies, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPolicies.
func (in IstioAuthorizationPoliciesAdditionalPolicies) DeepCopy() IstioAuthorizationPoliciesAdditionalPolicies {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPolicies)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPoliciesAdditionalPoliciesValue) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPoliciesValue) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPoliciesValue.
func (in *IstioAuthorizationPoliciesAdditionalPoliciesValue) DeepCopy() *IstioAuthorizationPoliciesAdditionalPoliciesValue {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPoliciesValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations) DeepCopy() IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueLabels) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPoliciesValueLabels) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPoliciesValueLabels.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueLabels) DeepCopy() IstioAuthorizationPoliciesAdditionalPoliciesValueLabels {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPoliciesValueLabels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPoliciesAdditionalPoliciesValueSpec) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPoliciesValueSpec) {
	*out = *in
	if in.Action != nil {
		in, out := &in.Action, &out.Action
		*out = new(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem, len(*in))
				for key, val := range *in {
					(*out)[key] = *val.DeepCopy()
				}
			}
		}
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPoliciesValueSpec.
func (in *IstioAuthorizationPoliciesAdditionalPoliciesValueSpec) DeepCopy() *IstioAuthorizationPoliciesAdditionalPoliciesValueSpec {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPoliciesValueSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem) DeepCopy() IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector) DeepCopyInto(out *IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector.
func (in IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector) DeepCopy() IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPoliciesCustomElem) DeepCopyInto(out *IstioAuthorizationPoliciesCustomElem) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(IstioAuthorizationPoliciesCustomElemAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(IstioAuthorizationPoliciesCustomElemLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(IstioAuthorizationPoliciesCustomElemSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesCustomElem.
func (in *IstioAuthorizationPoliciesCustomElem) DeepCopy() *IstioAuthorizationPoliciesCustomElem {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesCustomElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesCustomElemAnnotations) DeepCopyInto(out *IstioAuthorizationPoliciesCustomElemAnnotations) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesCustomElemAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesCustomElemAnnotations.
func (in IstioAuthorizationPoliciesCustomElemAnnotations) DeepCopy() IstioAuthorizationPoliciesCustomElemAnnotations {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesCustomElemAnnotations)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesCustomElemLabels) DeepCopyInto(out *IstioAuthorizationPoliciesCustomElemLabels) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesCustomElemLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesCustomElemLabels.
func (in IstioAuthorizationPoliciesCustomElemLabels) DeepCopy() IstioAuthorizationPoliciesCustomElemLabels {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesCustomElemLabels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioAuthorizationPoliciesCustomElemSpec) DeepCopyInto(out *IstioAuthorizationPoliciesCustomElemSpec) {
	{
		in := &in
		*out = make(IstioAuthorizationPoliciesCustomElemSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesCustomElemSpec.
func (in IstioAuthorizationPoliciesCustomElemSpec) DeepCopy() IstioAuthorizationPoliciesCustomElemSpec {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesCustomElemSpec)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPoliciesDefaults) DeepCopyInto(out *IstioAuthorizationPoliciesDefaults) {
	*out = *in
	if in.AllowInNamespace != nil {
		in, out := &in.AllowInNamespace, &out.AllowInNamespace
		*out = new(IstioAuthorizationPoliciesDefaultsAllowInNamespace)
		**out = **in
	}
	if in.DenyAll != nil {
		in, out := &in.DenyAll, &out.DenyAll
		*out = new(IstioAuthorizationPoliciesDefaultsDenyAll)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesDefaults.
func (in *IstioAuthorizationPoliciesDefaults) DeepCopy() *IstioAuthorizationPoliciesDefaults {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPoliciesDefaultsAllowInNamespace) DeepCopyInto(out *IstioAuthorizationPoliciesDefaultsAllowInNamespace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesDefaultsAllowInNamespace.
func (in *IstioAuthorizationPoliciesDefaultsAllowInNamespace) DeepCopy() *IstioAuthorizationPoliciesDefaultsAllowInNamespace {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesDefaultsAllowInNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioAuthorizationPoliciesDefaultsDenyAll) DeepCopyInto(out *IstioAuthorizationPoliciesDefaultsDenyAll) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioAuthorizationPoliciesDefaultsDenyAll.
func (in *IstioAuthorizationPoliciesDefaultsDenyAll) DeepCopy() *IstioAuthorizationPoliciesDefaultsDenyAll {
	if in == nil {
		return nil
	}
	out := new(IstioAuthorizationPoliciesDefaultsDenyAll)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioMtls) DeepCopyInto(out *IstioMtls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioMtls.
func (in *IstioMtls) DeepCopy() *IstioMtls {
	if in == nil {
		return nil
	}
	out := new(IstioMtls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioServiceEntries) DeepCopyInto(out *IstioServiceEntries) {
	*out = *in
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = make([]IstioServiceEntriesCustomElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioServiceEntries.
func (in *IstioServiceEntries) DeepCopy() *IstioServiceEntries {
	if in == nil {
		return nil
	}
	out := new(IstioServiceEntries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioServiceEntriesCustomElem) DeepCopyInto(out *IstioServiceEntriesCustomElem) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(IstioServiceEntriesCustomElemAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(IstioServiceEntriesCustomElemLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = make(IstioServiceEntriesCustomElemSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioServiceEntriesCustomElem.
func (in *IstioServiceEntriesCustomElem) DeepCopy() *IstioServiceEntriesCustomElem {
	if in == nil {
		return nil
	}
	out := new(IstioServiceEntriesCustomElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioServiceEntriesCustomElemAnnotations) DeepCopyInto(out *IstioServiceEntriesCustomElemAnnotations) {
	{
		in := &in
		*out = make(IstioServiceEntriesCustomElemAnnotations, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioServiceEntriesCustomElemAnnotations.
func (in IstioServiceEntriesCustomElemAnnotations) DeepCopy() IstioServiceEntriesCustomElemAnnotations {
	if in == nil {
		return nil
	}
	out := new(IstioServiceEntriesCustomElemAnnotations)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioServiceEntriesCustomElemLabels) DeepCopyInto(out *IstioServiceEntriesCustomElemLabels) {
	{
		in := &in
		*out = make(IstioServiceEntriesCustomElemLabels, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioServiceEntriesCustomElemLabels.
func (in IstioServiceEntriesCustomElemLabels) DeepCopy() IstioServiceEntriesCustomElemLabels {
	if in == nil {
		return nil
	}
	out := new(IstioServiceEntriesCustomElemLabels)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in IstioServiceEntriesCustomElemSpec) DeepCopyInto(out *IstioServiceEntriesCustomElemSpec) {
	{
		in := &in
		*out = make(IstioServiceEntriesCustomElemSpec, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioServiceEntriesCustomElemSpec.
func (in IstioServiceEntriesCustomElemSpec) DeepCopy() IstioServiceEntriesCustomElemSpec {
	if in == nil {
		return nil
	}
	out := new(IstioServiceEntriesCustomElemSpec)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSidecar) DeepCopyInto(out *IstioSidecar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSidecar.
func (in *IstioSidecar) DeepCopy() *IstioSidecar {
	if in == nil {
		return nil
	}
	out := new(IstioSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicies) DeepCopyInto(out *NetworkPolicies) {
	*out = *in
	if in.Additional != nil {
		in, out := &in.Additional, &out.Additional
		*out = make([]AdditionalPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdditionalPolicies != nil {
		in, out := &in.AdditionalPolicies, &out.AdditionalPolicies
		*out = make([]AdditionalPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultsAsHooks != nil {
		in, out := &in.DefaultsAsHooks, &out.DefaultsAsHooks
		*out = new(NetworkPoliciesDefaultsAsHooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(NetworkPoliciesEgress)
		(*in).DeepCopyInto(*out)
	}
	if in.HbonePortInjection != nil {
		in, out := &in.HbonePortInjection, &out.HbonePortInjection
		*out = new(NetworkPoliciesHbonePortInjection)
		**out = **in
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(NetworkPoliciesIngress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicies.
func (in *NetworkPolicies) DeepCopy() *NetworkPolicies {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesDefaultsAsHooks) DeepCopyInto(out *NetworkPoliciesDefaultsAsHooks) {
	*out = *in
	if in.DeletePolicies != nil {
		in, out := &in.DeletePolicies, &out.DeletePolicies
		*out = make([]NetworkPoliciesDefaultsAsHooksDeletePoliciesElem, len(*in))
		copy(*out, *in)
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = make([]NetworkPoliciesDefaultsAsHooksHooksElem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesDefaultsAsHooks.
func (in *NetworkPoliciesDefaultsAsHooks) DeepCopy() *NetworkPoliciesDefaultsAsHooks {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesDefaultsAsHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgress) DeepCopyInto(out *NetworkPoliciesEgress) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(NetworkPoliciesEgressDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.Definitions != nil {
		in, out := &in.Definitions, &out.Definitions
		*out = make(NetworkPoliciesEgressDefinitions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ExcludeCIDRs != nil {
		in, out := &in.ExcludeCIDRs, &out.ExcludeCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make(NetworkPoliciesEgressFrom, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgress.
func (in *NetworkPoliciesEgress) DeepCopy() *NetworkPoliciesEgress {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefaults) DeepCopyInto(out *NetworkPoliciesEgressDefaults) {
	*out = *in
	if in.AllowInNamespace != nil {
		in, out := &in.AllowInNamespace, &out.AllowInNamespace
		*out = new(NetworkPoliciesEgressDefaultsAllowInNamespace)
		**out = **in
	}
	if in.AllowIstiod != nil {
		in, out := &in.AllowIstiod, &out.AllowIstiod
		*out = new(NetworkPoliciesEgressDefaultsAllowIstiod)
		**out = **in
	}
	if in.AllowKubeDNS != nil {
		in, out := &in.AllowKubeDNS, &out.AllowKubeDNS
		*out = new(NetworkPoliciesEgressDefaultsAllowKubeDNS)
		**out = **in
	}
	if in.DenyAll != nil {
		in, out := &in.DenyAll, &out.DenyAll
		*out = new(NetworkPoliciesEgressDefaultsDenyAll)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefaults.
func (in *NetworkPoliciesEgressDefaults) DeepCopy() *NetworkPoliciesEgressDefaults {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefaultsAllowInNamespace) DeepCopyInto(out *NetworkPoliciesEgressDefaultsAllowInNamespace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefaultsAllowInNamespace.
func (in *NetworkPoliciesEgressDefaultsAllowInNamespace) DeepCopy() *NetworkPoliciesEgressDefaultsAllowInNamespace {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefaultsAllowInNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefaultsAllowIstiod) DeepCopyInto(out *NetworkPoliciesEgressDefaultsAllowIstiod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefaultsAllowIstiod.
func (in *NetworkPoliciesEgressDefaultsAllowIstiod) DeepCopy() *NetworkPoliciesEgressDefaultsAllowIstiod {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefaultsAllowIstiod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefaultsAllowKubeDNS) DeepCopyInto(out *NetworkPoliciesEgressDefaultsAllowKubeDNS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefaultsAllowKubeDNS.
func (in *NetworkPoliciesEgressDefaultsAllowKubeDNS) DeepCopy() *NetworkPoliciesEgressDefaultsAllowKubeDNS {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefaultsAllowKubeDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefaultsDenyAll) DeepCopyInto(out *NetworkPoliciesEgressDefaultsDenyAll) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefaultsDenyAll.
func (in *NetworkPoliciesEgressDefaultsDenyAll) DeepCopy() *NetworkPoliciesEgressDefaultsDenyAll {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefaultsDenyAll)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesEgressDefinitions) DeepCopyInto(out *NetworkPoliciesEgressDefinitions) {
	{
		in := &in
		*out = make(NetworkPoliciesEgressDefinitions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitions.
func (in NetworkPoliciesEgressDefinitions) DeepCopy() NetworkPoliciesEgressDefinitions {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefinitionsValue) DeepCopyInto(out *NetworkPoliciesEgressDefinitionsValue) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPoliciesEgressDefinitionsValuePortsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]NetworkPoliciesEgressDefinitionsValueToElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitionsValue.
func (in *NetworkPoliciesEgressDefinitionsValue) DeepCopy() *NetworkPoliciesEgressDefinitionsValue {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitionsValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefinitionsValuePortsElem) DeepCopyInto(out *NetworkPoliciesEgressDefinitionsValuePortsElem) {
	*out = *in
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(int)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(NetworkPoliciesEgressDefinitionsValuePortsElemProtocol)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitionsValuePortsElem.
func (in *NetworkPoliciesEgressDefinitionsValuePortsElem) DeepCopy() *NetworkPoliciesEgressDefinitionsValuePortsElem {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitionsValuePortsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefinitionsValueToElem) DeepCopyInto(out *NetworkPoliciesEgressDefinitionsValueToElem) {
	*out = *in
	if in.IPBlock != nil {
		in, out := &in.IPBlock, &out.IPBlock
		*out = new(NetworkPoliciesEgressDefinitionsValueToElemIPBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = make(NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = make(NetworkPoliciesEgressDefinitionsValueToElemPodSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitionsValueToElem.
func (in *NetworkPoliciesEgressDefinitionsValueToElem) DeepCopy() *NetworkPoliciesEgressDefinitionsValueToElem {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitionsValueToElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesEgressDefinitionsValueToElemIPBlock) DeepCopyInto(out *NetworkPoliciesEgressDefinitionsValueToElemIPBlock) {
	*out = *in
	if in.CIDR != nil {
		in, out := &in.CIDR, &out.CIDR
		*out = new(string)
		**out = **in
	}
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitionsValueToElemIPBlock.
func (in *NetworkPoliciesEgressDefinitionsValueToElemIPBlock) DeepCopy() *NetworkPoliciesEgressDefinitionsValueToElemIPBlock {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitionsValueToElemIPBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector) DeepCopyInto(out *NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector) {
	{
		in := &in
		*out = make(NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector.
func (in NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector) DeepCopy() NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesEgressDefinitionsValueToElemPodSelector) DeepCopyInto(out *NetworkPoliciesEgressDefinitionsValueToElemPodSelector) {
	{
		in := &in
		*out = make(NetworkPoliciesEgressDefinitionsValueToElemPodSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressDefinitionsValueToElemPodSelector.
func (in NetworkPoliciesEgressDefinitionsValueToElemPodSelector) DeepCopy() NetworkPoliciesEgressDefinitionsValueToElemPodSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressDefinitionsValueToElemPodSelector)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesEgressFrom) DeepCopyInto(out *NetworkPoliciesEgressFrom) {
	{
		in := &in
		*out = make(NetworkPoliciesEgressFrom, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesEgressFrom.
func (in NetworkPoliciesEgressFrom) DeepCopy() NetworkPoliciesEgressFrom {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesEgressFrom)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesHbonePortInjection) DeepCopyInto(out *NetworkPoliciesHbonePortInjection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesHbonePortInjection.
func (in *NetworkPoliciesHbonePortInjection) DeepCopy() *NetworkPoliciesHbonePortInjection {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesHbonePortInjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngress) DeepCopyInto(out *NetworkPoliciesIngress) {
	*out = *in
	if in.Defaults != nil {
		in, out := &in.Defaults, &out.Defaults
		*out = new(NetworkPoliciesIngressDefaults)
		(*in).DeepCopyInto(*out)
	}
	if in.Definitions != nil {
		in, out := &in.Definitions, &out.Definitions
		*out = make(NetworkPoliciesIngressDefinitions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make(NetworkPoliciesIngressTo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngress.
func (in *NetworkPoliciesIngress) DeepCopy() *NetworkPoliciesIngress {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefaults) DeepCopyInto(out *NetworkPoliciesIngressDefaults) {
	*out = *in
	if in.AllowInNamespace != nil {
		in, out := &in.AllowInNamespace, &out.AllowInNamespace
		*out = new(NetworkPoliciesIngressDefaultsAllowInNamespace)
		**out = **in
	}
	if in.AllowPrometheusToIstioSidecar != nil {
		in, out := &in.AllowPrometheusToIstioSidecar, &out.AllowPrometheusToIstioSidecar
		*out = new(NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar)
		**out = **in
	}
	if in.DenyAll != nil {
		in, out := &in.DenyAll, &out.DenyAll
		*out = new(NetworkPoliciesIngressDefaultsDenyAll)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefaults.
func (in *NetworkPoliciesIngressDefaults) DeepCopy() *NetworkPoliciesIngressDefaults {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefaultsAllowInNamespace) DeepCopyInto(out *NetworkPoliciesIngressDefaultsAllowInNamespace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefaultsAllowInNamespace.
func (in *NetworkPoliciesIngressDefaultsAllowInNamespace) DeepCopy() *NetworkPoliciesIngressDefaultsAllowInNamespace {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefaultsAllowInNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar) DeepCopyInto(out *NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar.
func (in *NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar) DeepCopy() *NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefaultsDenyAll) DeepCopyInto(out *NetworkPoliciesIngressDefaultsDenyAll) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefaultsDenyAll.
func (in *NetworkPoliciesIngressDefaultsDenyAll) DeepCopy() *NetworkPoliciesIngressDefaultsDenyAll {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefaultsDenyAll)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesIngressDefinitions) DeepCopyInto(out *NetworkPoliciesIngressDefinitions) {
	{
		in := &in
		*out = make(NetworkPoliciesIngressDefinitions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitions.
func (in NetworkPoliciesIngressDefinitions) DeepCopy() NetworkPoliciesIngressDefinitions {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefinitionsValue) DeepCopyInto(out *NetworkPoliciesIngressDefinitionsValue) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]NetworkPoliciesIngressDefinitionsValueFromElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPoliciesIngressDefinitionsValuePortsElem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitionsValue.
func (in *NetworkPoliciesIngressDefinitionsValue) DeepCopy() *NetworkPoliciesIngressDefinitionsValue {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitionsValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefinitionsValueFromElem) DeepCopyInto(out *NetworkPoliciesIngressDefinitionsValueFromElem) {
	*out = *in
	if in.IPBlock != nil {
		in, out := &in.IPBlock, &out.IPBlock
		*out = new(NetworkPoliciesIngressDefinitionsValueFromElemIPBlock)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = make(NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = make(NetworkPoliciesIngressDefinitionsValueFromElemPodSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitionsValueFromElem.
func (in *NetworkPoliciesIngressDefinitionsValueFromElem) DeepCopy() *NetworkPoliciesIngressDefinitionsValueFromElem {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitionsValueFromElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefinitionsValueFromElemIPBlock) DeepCopyInto(out *NetworkPoliciesIngressDefinitionsValueFromElemIPBlock) {
	*out = *in
	if in.CIDR != nil {
		in, out := &in.CIDR, &out.CIDR
		*out = new(string)
		**out = **in
	}
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitionsValueFromElemIPBlock.
func (in *NetworkPoliciesIngressDefinitionsValueFromElemIPBlock) DeepCopy() *NetworkPoliciesIngressDefinitionsValueFromElemIPBlock {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitionsValueFromElemIPBlock)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector) DeepCopyInto(out *NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector) {
	{
		in := &in
		*out = make(NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector.
func (in NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector) DeepCopy() NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesIngressDefinitionsValueFromElemPodSelector) DeepCopyInto(out *NetworkPoliciesIngressDefinitionsValueFromElemPodSelector) {
	{
		in := &in
		*out = make(NetworkPoliciesIngressDefinitionsValueFromElemPodSelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitionsValueFromElemPodSelector.
func (in NetworkPoliciesIngressDefinitionsValueFromElemPodSelector) DeepCopy() NetworkPoliciesIngressDefinitionsValueFromElemPodSelector {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitionsValueFromElemPodSelector)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPoliciesIngressDefinitionsValuePortsElem) DeepCopyInto(out *NetworkPoliciesIngressDefinitionsValuePortsElem) {
	*out = *in
	if in.EndPort != nil {
		in, out := &in.EndPort, &out.EndPort
		*out = new(int)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(NetworkPoliciesIngressDefinitionsValuePortsElemProtocol)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressDefinitionsValuePortsElem.
func (in *NetworkPoliciesIngressDefinitionsValuePortsElem) DeepCopy() *NetworkPoliciesIngressDefinitionsValuePortsElem {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressDefinitionsValuePortsElem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in NetworkPoliciesIngressTo) DeepCopyInto(out *NetworkPoliciesIngressTo) {
	{
		in := &in
		*out = make(NetworkPoliciesIngressTo, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPoliciesIngressTo.
func (in NetworkPoliciesIngressTo) DeepCopy() NetworkPoliciesIngressTo {
	if in == nil {
		return nil
	}
	out := new(NetworkPoliciesIngressTo)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Package) DeepCopyInto(out *Package) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Package.
func (in *Package) DeepCopy() *Package {
	if in == nil {
		return nil
	}
	out := new(Package)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Package) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageList) DeepCopyInto(out *PackageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Package, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageList.
func (in *PackageList) DeepCopy() *PackageList {
	if in == nil {
		return nil
	}
	out := new(PackageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PackageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageSpec) DeepCopyInto(out *PackageSpec) {
	*out = *in
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(Istio)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicies != nil {
		in, out := &in.NetworkPolicies, &out.NetworkPolicies
		*out = new(NetworkPolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = new(Routes)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageSpec.
func (in *PackageSpec) DeepCopy() *PackageSpec {
	if in == nil {
		return nil
	}
	out := new(PackageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PackageStatus) DeepCopyInto(out *PackageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedResources != nil {
		in, out := &in.AppliedResources, &out.AppliedResources
		*out = make([]AppliedResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PackageStatus.
func (in *PackageStatus) DeepCopy() *PackageStatus {
	if in == nil {
		return nil
	}
	out := new(PackageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Routes) DeepCopyInto(out *Routes) {
	*out = *in
	if in.Inbound != nil {
		in, out := &in.Inbound, &out.Inbound
		*out = make(RoutesInbound, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Outbound != nil {
		in, out := &in.Outbound, &out.Outbound
		*out = make(RoutesOutbound, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Routes.
func (in *Routes) DeepCopy() *Routes {
	if in == nil {
		return nil
	}
	out := new(Routes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RoutesInbound) DeepCopyInto(out *RoutesInbound) {
	{
		in := &in
		*out = make(RoutesInbound, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutesInbound.
func (in RoutesInbound) DeepCopy() RoutesInbound {
	if in == nil {
		return nil
	}
	out := new(RoutesInbound)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RoutesOutbound) DeepCopyInto(out *RoutesOutbound) {
	{
		in := &in
		*out = make(RoutesOutbound, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutesOutbound.
func (in RoutesOutbound) DeepCopy() RoutesOutbound {
	if in == nil {
		return nil
	}
	out := new(RoutesOutbound)
	in.DeepCopyInto(out)
	return *out
}
