// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.
// Post-processed by hack/schema-to-go.sh.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

type AdditionalPolicy struct {
	// Annotations for the network policy
	Annotations AdditionalPolicyAnnotations `json:"annotations,omitempty"`

	// Additional labels for the network policy
	Labels AdditionalPolicyLabels `json:"labels,omitempty"`

	// Name of the network policy
	Name string `json:"name"`

	// Raw NetworkPolicy spec
	Spec AdditionalPolicySpec `json:"spec"`
}

// Annotations for the network policy
type AdditionalPolicyAnnotations map[string]string

// Additional labels for the network policy
type AdditionalPolicyLabels map[string]string

// Raw NetworkPolicy spec
type AdditionalPolicySpec map[string]apiextensionsv1.JSON

// Istio service mesh configuration
type Istio struct {
	// Istio ambient configuration
	Ambient *IstioAmbient `json:"ambient,omitempty"`

	// Istio AuthorizationPolicies configuration for service mesh security
	AuthorizationPolicies *IstioAuthorizationPolicies `json:"authorizationPolicies,omitempty"`

	// Enable Istio integration
	Enabled bool `json:"enabled,omitempty"`

	// Mutual TLS configuration
	Mtls *IstioMtls `json:"mtls,omitempty"`

	// Prepend release name to istio resource names
	PrependReleaseName bool `json:"prependReleaseName,omitempty"`

	// Istio ServiceEntry resources configuration
	ServiceEntries *IstioServiceEntries `json:"serviceEntries,omitempty"`

	// Istio Sidecar resource configuration for outbound traffic control
	Sidecar *IstioSidecar `json:"sidecar,omitempty"`
}

// Istio ambient configuration
type IstioAmbient struct {
	// Enable ambient mode settings
	Enabled bool `json:"enabled,omitempty"`
}

// Istio AuthorizationPolicies configuration for service mesh security
type IstioAuthorizationPolicies struct {
	// Additional custom Istio AuthorizationPolicies (map structure to avoid override
	// issues)
	AdditionalPolicies IstioAuthorizationPoliciesAdditionalPolicies `json:"additionalPolicies,omitempty"`

	// List of custom Istio AuthorizationPolicy resources
	Custom []IstioAuthorizationPoliciesCustomElem `json:"custom,omitempty"`

	// Default authorization policies
	Defaults *IstioAuthorizationPoliciesDefaults `json:"defaults,omitempty"`

	// Enable generation of Istio AuthorizationPolicies
	Enabled bool `json:"enabled,omitempty"`

	// Generate Istio AuthorizationPolicies from NetworkPolicy configurations with
	// SPIFFE-based identity verification when service account identities are
	// specified
	GenerateFromNetpol bool `json:"generateFromNetpol,omitempty"`
}

// Additional custom Istio AuthorizationPolicies (map structure to avoid override
// issues)
type IstioAuthorizationPoliciesAdditionalPoliciesValue struct {
	// Annotations for the authorization policy
	Annotations IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations `json:"annotations,omitempty"`

	// Enable this authorization policy
	Enabled bool `json:"enabled,omitempty"`

	// Additional labels for the authorization policy
	Labels IstioAuthorizationPoliciesAdditionalPoliciesValueLabels `json:"labels,omitempty"`

	// Name of the authorization policy (optional, defaults to map key)
	Name *string `json:"name,omitempty"`

	// Namespace for the authorization policy (optional)
	Namespace *string `json:"namespace,omitempty"`

	// Istio AuthorizationPolicy spec
	Spec IstioAuthorizationPoliciesAdditionalPoliciesValueSpec `json:"spec"`
}

type IstioAuthorizationPoliciesAdditionalPolicies map[string]IstioAuthorizationPoliciesAdditionalPoliciesValue

// Annotations for the authorization policy
type IstioAuthorizationPoliciesAdditionalPoliciesValueAnnotations map[string]string

// Additional labels for the authorization policy
type IstioAuthorizationPoliciesAdditionalPoliciesValueLabels map[string]string

// Istio AuthorizationPolicy spec
type IstioAuthorizationPoliciesAdditionalPoliciesValueSpec struct {
	// Action to take when rules match
	Action *IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction `json:"action,omitempty"`

	// List of authorization rules
	Rules []IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem `json:"rules,omitempty"`

	// Pod selector for the authorization policy
	Selector IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector `json:"selector,omitempty"`
}

type IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction string

const IstioAuthorizationPoliciesAdditionalPoliciesValueSpecActionALLOW IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction = "ALLOW"
const IstioAuthorizationPoliciesAdditionalPoliciesValueSpecActionAUDIT IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction = "AUDIT"
const IstioAuthorizationPoliciesAdditionalPoliciesValueSpecActionCUSTOM IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction = "CUSTOM"
const IstioAuthorizationPoliciesAdditionalPoliciesValueSpecActionDENY IstioAuthorizationPoliciesAdditionalPoliciesValueSpecAction = "DENY"

type IstioAuthorizationPoliciesAdditionalPoliciesValueSpecRulesElem map[string]apiextensionsv1.JSON

// Pod selector for the authorization policy
type IstioAuthorizationPoliciesAdditionalPoliciesValueSpecSelector map[string]apiextensionsv1.JSON

type IstioAuthorizationPoliciesCustomElem struct {
	// Annotations for the AuthorizationPolicy
	Annotations IstioAuthorizationPoliciesCustomElemAnnotations `json:"annotations,omitempty"`

	// Additional labels for the AuthorizationPolicy
	Labels IstioAuthorizationPoliciesCustomElemLabels `json:"labels,omitempty"`

	// Name of the AuthorizationPolicy
	Name string `json:"name"`

	// Istio AuthorizationPolicy spec
	Spec IstioAuthorizationPoliciesCustomElemSpec `json:"spec"`
}

// Annotations for the AuthorizationPolicy
type IstioAuthorizationPoliciesCustomElemAnnotations map[string]string

// Additional labels for the AuthorizationPolicy
type IstioAuthorizationPoliciesCustomElemLabels map[string]string

// Istio AuthorizationPolicy spec
type IstioAuthorizationPoliciesCustomElemSpec map[string]apiextensionsv1.JSON

// Default authorization policies
type IstioAuthorizationPoliciesDefaults struct {
	// Allow ingress from same namespace
	AllowInNamespace *IstioAuthorizationPoliciesDefaultsAllowInNamespace `json:"allowInNamespace,omitempty"`

	// Deny all ingress by default (allow-nothing policy)
	DenyAll *IstioAuthorizationPoliciesDefaultsDenyAll `json:"denyAll,omitempty"`

	// Enable all default authorization policies
	Enabled bool `json:"enabled,omitempty"`
}

// Allow ingress from same namespace
type IstioAuthorizationPoliciesDefaultsAllowInNamespace struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Deny all ingress by default (allow-nothing policy)
type IstioAuthorizationPoliciesDefaultsDenyAll struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Mutual TLS configuration
type IstioMtls struct {
	// mTLS mode (STRICT, PERMISSIVE, or DISABLE)
	Mode IstioMtlsMode `json:"mode,omitempty"`
}

type IstioMtlsMode string

const IstioMtlsModeDISABLE IstioMtlsMode = "DISABLE"
const IstioMtlsModePERMISSIVE IstioMtlsMode = "PERMISSIVE"
const IstioMtlsModeSTRICT IstioMtlsMode = "STRICT"

// Istio ServiceEntry resources configuration
type IstioServiceEntries struct {
	// List of custom Istio ServiceEntry resources
	Custom []IstioServiceEntriesCustomElem `json:"custom,omitempty"`
}

type IstioServiceEntriesCustomElem struct {
	// Annotations for the ServiceEntry
	Annotations IstioServiceEntriesCustomElemAnnotations `json:"annotations,omitempty"`

	// Additional labels for the ServiceEntry
	Labels IstioServiceEntriesCustomElemLabels `json:"labels,omitempty"`

	// Name of the ServiceEntry
	Name string `json:"name"`

	// Istio ServiceEntry spec
	Spec IstioServiceEntriesCustomElemSpec `json:"spec"`
}

// Annotations for the ServiceEntry
type IstioServiceEntriesCustomElemAnnotations map[string]string

// Additional labels for the ServiceEntry
type IstioServiceEntriesCustomElemLabels map[string]string

// Istio ServiceEntry spec
type IstioServiceEntriesCustomElemSpec map[string]apiextensionsv1.JSON

// Istio Sidecar resource configuration for outbound traffic control
type IstioSidecar struct {
	// Enable Istio Sidecar resource (restricts outbound traffic)
	Enabled bool `json:"enabled,omitempty"`

	// Outbound traffic policy mode (REGISTRY_ONLY or ALLOW_ANY)
	OutboundTrafficPolicyMode IstioSidecarOutboundTrafficPolicyMode `json:"outboundTrafficPolicyMode,omitempty"`
}

type IstioSidecarOutboundTrafficPolicyMode string

const IstioSidecarOutboundTrafficPolicyModeALLOWANY IstioSidecarOutboundTrafficPolicyMode = "ALLOW_ANY"
const IstioSidecarOutboundTrafficPolicyModeREGISTRYONLY IstioSidecarOutboundTrafficPolicyMode = "REGISTRY_ONLY"

// Network policies configuration for the application
type NetworkPolicies struct {
	// Additional raw network policies (also accepts 'additional' for backwards
	// compatibility)
	Additional []AdditionalPolicy `json:"additional,omitempty"`

	// Additional raw network policies (also accepts 'additional' for backwards
	// compatibility)
	AdditionalPolicies []AdditionalPolicy `json:"additionalPolicies,omitempty"`

	// Create hook versions of default policies in addition to regular versions
	DefaultsAsHooks *NetworkPoliciesDefaultsAsHooks `json:"defaultsAsHooks,omitempty"`

	// Egress network policy configuration
	Egress *NetworkPoliciesEgress `json:"egress,omitempty"`

	// Enable network policies
	Enabled bool `json:"enabled,omitempty"`

	// Istio HBONE port injection configuration
	HbonePortInjection *NetworkPoliciesHbonePortInjection `json:"hbonePortInjection,omitempty"`

	// Ingress network policy configuration
	Ingress *NetworkPoliciesIngress `json:"ingress,omitempty"`

	// Prepend release name to network policy names
	PrependReleaseName bool `json:"prependReleaseName,omitempty"`
}

// Create hook versions of default policies in addition to regular versions
type NetworkPoliciesDefaultsAsHooks struct {
	// Helm hook delete policies
	DeletePolicies []NetworkPoliciesDefaultsAsHooksDeletePoliciesElem `json:"deletePolicies,omitempty"`

	// Enable hook creation for default policies (creates both regular and hook
	// versions)
	Enabled bool `json:"enabled,omitempty"`

	// Helm hook types
	Hooks []NetworkPoliciesDefaultsAsHooksHooksElem `json:"hooks,omitempty"`

	// Helm hook weight for execution order
	Weight int `json:"weight,omitempty"`
}

type NetworkPoliciesDefaultsAsHooksDeletePoliciesElem string

const NetworkPoliciesDefaultsAsHooksDeletePoliciesElemBeforeHookCreation NetworkPoliciesDefaultsAsHooksDeletePoliciesElem = "before-hook-creation"
const NetworkPoliciesDefaultsAsHooksDeletePoliciesElemHookFailed NetworkPoliciesDefaultsAsHooksDeletePoliciesElem = "hook-failed"
const NetworkPoliciesDefaultsAsHooksDeletePoliciesElemHookSucceeded NetworkPoliciesDefaultsAsHooksDeletePoliciesElem = "hook-succeeded"

type NetworkPoliciesDefaultsAsHooksHooksElem string

const NetworkPoliciesDefaultsAsHooksHooksElemPostDelete NetworkPoliciesDefaultsAsHooksHooksElem = "post-delete"
const NetworkPoliciesDefaultsAsHooksHooksElemPostInstall NetworkPoliciesDefaultsAsHooksHooksElem = "post-install"
const NetworkPoliciesDefaultsAsHooksHooksElemPostRollback NetworkPoliciesDefaultsAsHooksHooksElem = "post-rollback"
const NetworkPoliciesDefaultsAsHooksHooksElemPostUpgrade NetworkPoliciesDefaultsAsHooksHooksElem = "post-upgrade"
const NetworkPoliciesDefaultsAsHooksHooksElemPreDelete NetworkPoliciesDefaultsAsHooksHooksElem = "pre-delete"
const NetworkPoliciesDefaultsAsHooksHooksElemPreInstall NetworkPoliciesDefaultsAsHooksHooksElem = "pre-install"
const NetworkPoliciesDefaultsAsHooksHooksElemPreRollback NetworkPoliciesDefaultsAsHooksHooksElem = "pre-rollback"
const NetworkPoliciesDefaultsAsHooksHooksElemPreUpgrade NetworkPoliciesDefaultsAsHooksHooksElem = "pre-upgrade"
const NetworkPoliciesDefaultsAsHooksHooksElemTest NetworkPoliciesDefaultsAsHooksHooksElem = "test"

// Egress network policy configuration
type NetworkPoliciesEgress struct {
	// Default egress policies
	Defaults *NetworkPoliciesEgressDefaults `json:"defaults,omitempty"`

	// Custom egress rule definitions that can be referenced
	Definitions NetworkPoliciesEgressDefinitions `json:"definitions,omitempty"`

	// CIDRs to exclude from all ipBlock egress policies (except literals)
	ExcludeCIDRs []string `json:"excludeCIDRs,omitempty"`

	// Egress rules from local pods
	From NetworkPoliciesEgressFrom `json:"from,omitempty"`
}

// Default egress policies
type NetworkPoliciesEgressDefaults struct {
	// Allow egress within the same namespace
	AllowInNamespace *NetworkPoliciesEgressDefaultsAllowInNamespace `json:"allowInNamespace,omitempty"`

	// Allow sidecar-mode Istio control plane communication (TCP port 15012). Not
	// rendered when ambient mode is enabled.
	AllowIstiod *NetworkPoliciesEgressDefaultsAllowIstiod `json:"allowIstiod,omitempty"`

	// Allow DNS resolution (TCP/UDP port 53)
	AllowKubeDNS *NetworkPoliciesEgressDefaultsAllowKubeDNS `json:"allowKubeDns,omitempty"`

	// Deny all egress by default
	DenyAll *NetworkPoliciesEgressDefaultsDenyAll `json:"denyAll,omitempty"`

	// Enable all default egress policies
	Enabled bool `json:"enabled,omitempty"`
}

// Allow egress within the same namespace
type NetworkPoliciesEgressDefaultsAllowInNamespace struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Allow sidecar-mode Istio control plane communication (TCP port 15012). Not
// rendered when ambient mode is enabled.
type NetworkPoliciesEgressDefaultsAllowIstiod struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Allow DNS resolution (TCP/UDP port 53)
type NetworkPoliciesEgressDefaultsAllowKubeDNS struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Deny all egress by default
type NetworkPoliciesEgressDefaultsDenyAll struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Custom egress rule definitions that can be referenced
type NetworkPoliciesEgressDefinitionsValue struct {
	// List of ports
	Ports []NetworkPoliciesEgressDefinitionsValuePortsElem `json:"ports,omitempty"`

	// List of egress destinations
	To []NetworkPoliciesEgressDefinitionsValueToElem `json:"to,omitempty"`
}

type NetworkPoliciesEgressDefinitions map[string]NetworkPoliciesEgressDefinitionsValue

type NetworkPoliciesEgressDefinitionsValuePortsElem struct {
	// End port for port range specifications
	EndPort *int `json:"endPort,omitempty"`

	// Port corresponds to the JSON schema field "port".
	Port *intstr.IntOrString `json:"port,omitempty"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol *NetworkPoliciesEgressDefinitionsValuePortsElemProtocol `json:"protocol,omitempty"`
}

type NetworkPoliciesEgressDefinitionsValuePortsElemProtocol string

const NetworkPoliciesEgressDefinitionsValuePortsElemProtocolSCTP NetworkPoliciesEgressDefinitionsValuePortsElemProtocol = "SCTP"
const NetworkPoliciesEgressDefinitionsValuePortsElemProtocolTCP NetworkPoliciesEgressDefinitionsValuePortsElemProtocol = "TCP"
const NetworkPoliciesEgressDefinitionsValuePortsElemProtocolUDP NetworkPoliciesEgressDefinitionsValuePortsElemProtocol = "UDP"

type NetworkPoliciesEgressDefinitionsValueToElem struct {
	// IP CIDR block
	IPBlock *NetworkPoliciesEgressDefinitionsValueToElemIPBlock `json:"ipBlock,omitempty"`

	// Kubernetes namespace selector
	NamespaceSelector NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector `json:"namespaceSelector,omitempty"`

	// Kubernetes pod selector
	PodSelector NetworkPoliciesEgressDefinitionsValueToElemPodSelector `json:"podSelector,omitempty"`
}

// IP CIDR block
type NetworkPoliciesEgressDefinitionsValueToElemIPBlock struct {
	// CIDR corresponds to the JSON schema field "cidr".
	CIDR *string `json:"cidr,omitempty"`

	// Except corresponds to the JSON schema field "except".
	Except []string `json:"except,omitempty"`
}

// Kubernetes namespace selector
type NetworkPoliciesEgressDefinitionsValueToElemNamespaceSelector map[string]apiextensionsv1.JSON

// Kubernetes pod selector
type NetworkPoliciesEgressDefinitionsValueToElemPodSelector map[string]apiextensionsv1.JSON

// Egress rules from local pods
type NetworkPoliciesEgressFrom map[string]apiextensionsv1.JSON

// Istio HBONE port injection configuration
type NetworkPoliciesHbonePortInjection struct {
	// Enable/disable HBONE port (15008) injection into NetworkPolicy rules when ports
	// are specified; ambient mode enables this automatically
	Enabled bool `json:"enabled,omitempty"`
}

// Ingress network policy configuration
type NetworkPoliciesIngress struct {
	// Default ingress policies
	Defaults *NetworkPoliciesIngressDefaults `json:"defaults,omitempty"`

	// Custom ingress rule definitions that can be referenced
	Definitions NetworkPoliciesIngressDefinitions `json:"definitions,omitempty"`

	// Ingress rules to local pods
	To NetworkPoliciesIngressTo `json:"to,omitempty"`
}

// Default ingress policies
type NetworkPoliciesIngressDefaults struct {
	// Allow ingress from same namespace
	AllowInNamespace *NetworkPoliciesIngressDefaultsAllowInNamespace `json:"allowInNamespace,omitempty"`

	// Allow ingress from Prometheus in monitoring namespace (TCP port 15020)
	AllowPrometheusToIstioSidecar *NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar `json:"allowPrometheusToIstioSidecar,omitempty"`

	// Deny all ingress by default
	DenyAll *NetworkPoliciesIngressDefaultsDenyAll `json:"denyAll,omitempty"`

	// Enable all default ingress policies
	Enabled bool `json:"enabled,omitempty"`
}

// Allow ingress from same namespace
type NetworkPoliciesIngressDefaultsAllowInNamespace struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Allow ingress from Prometheus in monitoring namespace (TCP port 15020)
type NetworkPoliciesIngressDefaultsAllowPrometheusToIstioSidecar struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Deny all ingress by default
type NetworkPoliciesIngressDefaultsDenyAll struct {
	// Enabled corresponds to the JSON schema field "enabled".
	Enabled bool `json:"enabled,omitempty"`
}

// Custom ingress rule definitions that can be referenced
type NetworkPoliciesIngressDefinitionsValue struct {
	// List of ingress sources
	From []NetworkPoliciesIngressDefinitionsValueFromElem `json:"from,omitempty"`

	// List of ports
	Ports []NetworkPoliciesIngressDefinitionsValuePortsElem `json:"ports,omitempty"`
}

type NetworkPoliciesIngressDefinitions map[string]NetworkPoliciesIngressDefinitionsValue

type NetworkPoliciesIngressDefinitionsValueFromElem struct {
	// IP CIDR block
	IPBlock *NetworkPoliciesIngressDefinitionsValueFromElemIPBlock `json:"ipBlock,omitempty"`

	// Kubernetes namespace selector
	NamespaceSelector NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector `json:"namespaceSelector,omitempty"`

	// Kubernetes pod selector
	PodSelector NetworkPoliciesIngressDefinitionsValueFromElemPodSelector `json:"podSelector,omitempty"`
}

// IP CIDR block
type NetworkPoliciesIngressDefinitionsValueFromElemIPBlock struct {
	// CIDR corresponds to the JSON schema field "cidr".
	CIDR *string `json:"cidr,omitempty"`

	// Except corresponds to the JSON schema field "except".
	Except []string `json:"except,omitempty"`
}

// Kubernetes namespace selector
type NetworkPoliciesIngressDefinitionsValueFromElemNamespaceSelector map[string]apiextensionsv1.JSON

// Kubernetes pod selector
type NetworkPoliciesIngressDefinitionsValueFromElemPodSelector map[string]apiextensionsv1.JSON

type NetworkPoliciesIngressDefinitionsValuePortsElem struct {
	// End port for port range specifications
	EndPort *int `json:"endPort,omitempty"`

	// Port corresponds to the JSON schema field "port".
	Port *intstr.IntOrString `json:"port,omitempty"`

	// Protocol corresponds to the JSON schema field "protocol".
	Protocol *NetworkPoliciesIngressDefinitionsValuePortsElemProtocol `json:"protocol,omitempty"`
}

type NetworkPoliciesIngressDefinitionsValuePortsElemProtocol string

const NetworkPoliciesIngressDefinitionsValuePortsElemProtocolSCTP NetworkPoliciesIngressDefinitionsValuePortsElemProtocol = "SCTP"
const NetworkPoliciesIngressDefinitionsValuePortsElemProtocolTCP NetworkPoliciesIngressDefinitionsValuePortsElemProtocol = "TCP"
const NetworkPoliciesIngressDefinitionsValuePortsElemProtocolUDP NetworkPoliciesIngressDefinitionsValuePortsElemProtocol = "UDP"

// Ingress rules to local pods
type NetworkPoliciesIngressTo map[string]apiextensionsv1.JSON

// Istio VirtualService and gateway configuration for routing traffic to
// applications
type Routes struct {
	// Inbound routes configuration
	Inbound RoutesInbound `json:"inbound,omitempty"`

	// Outbound routes configuration
	Outbound RoutesOutbound `json:"outbound,omitempty"`

	// Prepend release name to route resource names
	PrependReleaseName bool `json:"prependReleaseName,omitempty"`
}

// Inbound routes configuration
type RoutesInbound map[string]apiextensionsv1.JSON

// Outbound routes configuration
type RoutesOutbound map[string]apiextensionsv1.JSON
